# Generated by Django 5.2.1 on 2025-10-31 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0002_newspost_delete_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cabinet/library/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('alt_text', models.CharField(blank=True, help_text='Optional description', max_length=200)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fm.gallery')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='fm.mediafile')),
            ],
        ),
        migrations.AlterField(
            model_name='archiveprogram',
            name='audio_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archive_audio', to='fm.mediafile'),
        ),
        migrations.AlterField(
            model_name='archiveprogram',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_images', to='fm.mediafile'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_images', to='fm.mediafile'),
        ),
        migrations.AlterField(
            model_name='page',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_images', to='fm.mediafile'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profile_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_images', to='fm.mediafile'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider_images', to='fm.mediafile')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
