# Generated by Django 5.2.1 on 2025-10-31 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0003_gallery_mediafile_galleryimage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logo', to='fm.mediafile')),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logo',
            },
        ),
    ]
