# Generated by Django 5.2.1 on 2025-11-02 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0004_sitelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'Saturday'), (2, 'Sunday'), (3, 'Monday'), (4, 'Tuesday'), (5, 'Wednesday'), (6, 'Thursday'), (7, 'Friday')]),
        ),
    ]
