# Generated by Django 5.2.1 on 2025-11-14 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0005_alter_programschedule_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='submitted_at',
            new_name='sent_at',
        ),
    ]
