# Generated by Django 5.2.6 on 2026-04-19 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fm', '0006_rename_submitted_at_contactmessage_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programschedule',
            name='day',
            field=models.IntegerField(choices=[(1, 'Wednesday'), (2, 'Thursday'), (3, 'Friday'), (4, 'Saturday'), (5, 'Sunday'), (6, 'Monday'), (7, 'Tuesday')]),
        ),
    ]
